### ISSUE TITLE
Message pack fails to load dumped data

### ISSUE THREAD

**Issue by Kronuz** [msgpack/msgpack-python#173]
If I dump a dictionary which keys are tuples, msgpack fails to load it

```python
>>> msgpack.loads(msgpack.dumps({(1,2,3): 1}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 139, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:139)
TypeError: unhashable type: 'list'
```

The thing is msgpack loads the tuple as a list, but fails to convert it to a tuple before adding it to the dictionary?

**Comment by methane** [comment]
msgpack doesn't distinguish tuple and list like json.

```
>>> import json
>>> json.dumps((1,2,3))
'[1, 2, 3]'
>>> json.dumps([1,2,3])
'[1, 2, 3]'
```

But msgpack doesn't prohibit use list as key of mapping.  It's up to applications.
So this is not a bug.  It's spec you should know.

Unpacker has `use_list` option and it's default is True.
You can False to it to unpack sequence to tuple instead of list.
