### ISSUE TITLE
release schedule

### ISSUE THREAD

**Issue by vEpiphyte** [msgpack/msgpack-python#244]
Is there a plan for a next release of msgpack-python?

**Comment by brownan** [comment]
I was just wondering this myself. I could personally make use of the support for packing memoryview objects, which was merged in Jan 2016, but seems to have not yet made it into a release?

**Comment by lbolla** [comment]
It would be useful to at least bump the current version to something like 0.5.0a1 so that `pip install`ing it from git would not conflict with 0.4.8 currently in PyPi.

**Comment by vEpiphyte** [comment]
@browman I saw there was a 0.4.8 release in july 2016. did that not include the memoryview feature?

**Comment by methane** [comment]
I can't release master branch because I can't make final decision about some API designs.

For example, I prefer simplicity to massive small features required by ~1% users.
Then, should I accept tuple when `strict_types=True`?
I don't want adding new `accept_tuple` option.

I don't have time to considering future roadmap and some final decision in this year.

**Comment by brownan** [comment]
@methane Okay, I understand. Since I'm not familiar with all the details of the decisions that need making, I'm not sure my opinion would be worth much right now.  Does the master branch represent your current preferred design? If so, I'll try that out and provide feedback.

@vEpiphyte the commit I'm referring to (31adc5a) only made it onto the master branch, and hasn't made it into a release.
