### ISSUE TITLE
Python 3 support for numpy.int64

### ISSUE THREAD

**Issue by fersarr** [msgpack/msgpack-python#344]
I think this line:
https://github.com/msgpack/msgpack-python/blob/381c2eff5f8ee0b8669fd6daf1fd1ecaffe7c931/msgpack/fallback.py#L15

should include `numpy.int64`, because in `Python 3`, `numpy.int64` is no longer a class of `int`. Read more about that here: http://numpy-discussion.10968.n7.nabble.com/Python-3-and-isinstance-np-int64-42-int-td40531.html

Previously, In `Python 2`, we were able to do:
```
>>> msgpack.packb([np.int64(3)], encoding='utf-8')
'\x91\x03'
```
but in `Python 3`:

```
msgpack.packb([np.int64(3)], encoding='utf-8')
...
File "/users/is/ahlpypi/medusa_egg_cache/36-1/m/msgpack_python-0.5.4-py3.6-linux-x86_64.egg/msgpack/fallback.py", line 848, in _pack                                                                                                                _serialisation.py:98 (0 hits)
    raise TypeError("Cannot serialize %r" % (obj, ))                                                                                                                                                                                                  test_hdf5_pytable.py:297 (0 hits)
TypeError: Cannot serialize 3
```

**Comment by jfolz** [comment]
That would make numpy a dependency of msgpack.
msgpack is used by pip, so that would (at some point) make pip depend on numpy... so no.
There's also 9 other types beside `int64` that you'd want to add, so this is not the way to do it.
`isinstance(o, numbers.Integral)` could work, but there's not C-API equivalent. [This](https://docs.python.org/3/c-api/number.html) is the closest I think and it does not distinguish between integers and floats.

**Comment by jfolz** [comment]
[msgpack_numpy](https://pypi.org/project/msgpack-numpy/) should deal with scalars just fine.

**Comment by methane** [comment]
I know numpy is important part of Python ecosystem.
But keeping msgpack clean, simple, lightweight, fast, and maintainable is the most important for me.

Think this project is like json package in Python stdlib.  It doesn't support numpy too.
I won't add features not supported by json and major msgpack libraries in other languages.

**Comment by fersarr** [comment]
ok, understood! thanks for the explanation

**Comment by jfolz** [comment]
> I've actually run into this before and would appreciate the functionality.
> it's not super clean, but you could do something like this, which keeps numpy as a non dependency.

[It's not just `int64` though](https://docs.scipy.org/doc/numpy/user/basics.types.html). Right now I don't see any other way then checking for all these types to handle numpy scalars correctly. It would be more confusing if there's some types that are handled while others are not.

**Comment by pfeatherstone** [comment]
> I know numpy is important part of Python ecosystem.
> But keeping msgpack clean, simple, lightweight, fast, and maintainable is the most important for me.
> 
> Think this project is like json package in Python stdlib. It doesn't support numpy too.
> I won't add features not supported by json and major msgpack libraries in other languages.

@methane  I can understand the ethos. However, using python lists is a killer. I was using msgpack to serialise very large ```complex<float>``` arrays in C++ and unpacking them in python. It was way too slow. I ended up wrapping a ```read``` function using pybind11 to call a C++ function. At which point i decided to switch to another serialisation format like yas which has better size. It's a shame though because msgpack is great. I get that this repo should be clean of dependencies, but maybe using numpy would speed things up. Just something to ponder on.

**Comment by jfolz** [comment]
Food for thought: pip uses msgpack internally. Adding numpy as a dependency to msgpack would make pip depend on numpy :)

However, implementing some sort of API that takes an encoded msgpack array, creates a [buffer](https://docs.python.org/3/c-api/buffer.html#bufferobjects) object, wraps it in a [memoryview](https://docs.python.org/3/c-api/memoryview.html), which you can throw into [numpy.asarray](https://numpy.org/doc/stable/reference/generated/numpy.asarray.html#numpy.asarray)...

**Comment by pfeatherstone** [comment]
> Food for thought: pip uses msgpack internally. Adding numpy as a dependency to msgpack would make pip depend on numpy :)

I had no idea. Then yes a "higher level" API would be more suitable then.

**Comment by jfolz** [comment]
IMO the most awesomest thing would be if msgpack had native support for ND arrays ;)
