### ISSUE TITLE
msgpack imposes the size limit on the field: ValueError: 1398490 exceeds max_bin_len(1048576)

### ISSUE THREAD

**Issue by yurivict** [msgpack/msgpack-python#360]
I discovered it in the ```veles``` project, see https://github.com/codilime/veles/issues/446

py36-msgpack-0.6.1
FreeBSD 12

**Comment by jfolz** [comment]
That's a DOS protection feature. `unpackb` defaults to limits such that an unpacked object cannot consume more memory than the original message. Otherwise a malicious 5 byte message could make msgpack try to allocate 4G of memory. `Unpacker` defaults to a max of 1M for buffers which can be increased by setting `max_buffer_size`.

**Comment by yurivict** [comment]
Thank you, this solves the problem.
