### ISSUE TITLE
Mark 1.0.0 as a release on Github

### ISSUE THREAD

**Issue by tasn** [msgpack/msgpack-python#430]
Github currently shows the latest release as 0.6.1 because 1.0.0 is only marked as a tag and not as a github release.

I found it very confusing that I had 1.0.0 installed locally while the release here was 0.6.1 and I thought I may have gotten the wrong package.

Please consider marking the 1.0.0 as a release here too.

**Comment by methane** [comment]
I doesn't Github Release for release management.  I used it only for put artifacts from CI (AppVeyor).
But now I use Github Actions for building wheels and no need to use Release for saving wheels.
That's why no v1.0.0 in Releases. Sorry for confusion.

I deleted all releases except pre releases. Github doesn't show the "latest release" for now.

**Comment by tasn** [comment]
As good of a solution, thanks!
