### ISSUE TITLE
How to make a class be able to get packed by msgpack

### ISSUE THREAD

**Issue by ceremcem** [msgpack/msgpack-python#96]
Hi, 

I'm trying to use zerorpc, which uses msgpack. One of my custom classes can't be packed by msgpack. Here is the traceback: 
```
msgpack.dumps(CcaAsyncMotorTask("test"))
*** TypeError: can't serialize <__main__.CcaAsyncMotorTask object at 0xf05890>
```

The same instance can be pickled:
```
pickle.dumps(CcaAsyncMotorTask("test"))
"ccopy_reg\n_reconstructor\np0\n(c__main__\nCcaAsyncMotorTask\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\n(dp5\nS'_allow_exec_signals'\np6\n(dp7\nsS'current_state'\np8\nS'stopped'\np9\nsS'name'\np10\nS'test'\np11\nsS'_duration'\np12\nI0\nsS'_allow_exec_signal'\np13\ng0\n(ccca_signal\nCcaSignal\np14\ng2\nNtp15\nRp16\n(dp17\nS'_CcaSignal__val0'\np18\nI00\nsS'_CcaSignal__readers_got_last_change'\np19\n(dp20\nsS'_CcaSignal__val'\np21\nI00\nsbsb."
```

I don't know why msgpack can not pack this instance. What should I change in the class?

**Comment by methane** [comment]
https://github.com/msgpack/msgpack-python#packingunpacking-of-custom-data-type

**Comment by PGryllos** [comment]
sorry but it's not clear to me what the suggestion is about this. How is someone supposed to create the string representation of the custom class object? datetime objects happen to offer back and forth string conversion. But that's not the general case. Is someone supposed to use pickle to create the string representation? If not (which I guess not otherwise what is the purpose) then is the general suggestion?

**Comment by jfolz** [comment]
You simple send all data necessary to reconstruct the object at the other end (e.g. to pass to init or similar creation methods). Pickle does do that for most (not all) objects.
The documentation gives you all the information you need. For a more complex example see [msgpack_numpy](https://github.com/lebedov/msgpack-numpy/blob/802f1e55e631aa8fb7789ffcdd9dcb5cfa928a9f/msgpack_numpy.py#L31).
